### ISSUE TITLE
Better identification

### ISSUE THREAD

**Issue by Dendraspis** [jpsdr/x265#6]
It would be nice if your version could identify itself as yours, rather than being made by @Patman86. 

While it's great to honor him and/or make visible, that his Repo was the base for your modifications, a better identification that `Mod by Patman` would be great, especially to avoid confusion, wrong assignment and to be able to differ between both Repos.
Something like `Mod by Patman/JPSDR` or `Mod by Patman and JPSDR` or `Mod by JPSDR, based on mod by Patman` would be nice.

At least affected (could be incomplete):
https://github.com/jpsdr/x265/blob/x265_mod/source/x265cli.cpp#L41-L42
https://github.com/jpsdr/x265/blob/x265_mod/source/encoder/api.cpp#L117-L118

At that point #4 would be also very useful.

**Comment by jpsdr** [comment]
I just discovered this... I just thought of the same thing for the last release.
