### ISSUE TITLE
NVE 7.54 Does not accept the formats  ProRes 4444 and 4444 XQ

### ISSUE THREAD

**Issue by Victory61** [jpsdr/x265#7]
Good morning.
I have tried several files with both Prores 4444 and ProRes 4444 XQ formats, I detect 2 different types of errors
With ProRes 422 HQ format it is accepted and is encoded without problems.
I don't know what could be the reason that 4444 and 4444 XQ formats are accepted....
Thanks

https://i.postimg.cc/85ryvmXX/Pro-Res-4444.png

https://i.postimg.cc/5ydsSQZ4/Pro-Res-4444-XQ.png

**Comment by jpsdr** [comment]
Sorry, i just build the .exe, can't help you with this.
